[workspace]
resolver = "2"
members = [
    "ssl-cert-monitor-lambda",
    "ssl-cert-reporter-lambda",
]

[workspace.package]
edition = "2021"
license = "MIT"
readme = "README.md"
authors = ["theirix <theirix@gmail.com>"]

[profile.dev]
debug = 0
